# Generated by Django 3.1 on 2020-09-08 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_whenmade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='whenMade',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
