# Generated by Django 3.1 on 2020-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='indexDescription',
            field=models.CharField(default='Lorem ipsum dolor sit amet', max_length=255),
            preserve_default=False,
        ),
    ]
