# Generated by Django 3.1 on 2020-09-10 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200908_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='product',
            new_name='title',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='category',
            field=models.CharField(default='Title - Demo Edited', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor sit amet', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='imageURL',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='indexDescription',
            field=models.CharField(default='Lorem', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='numberBids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='owner',
            field=models.CharField(default='aryanj', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='price',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='whenMade',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
