# Generated by Django 3.1 on 2020-09-12 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200910_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='indexDescription',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='numberBids',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='whenMade',
        ),
    ]
