# Generated by Django 3.1 on 2020-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200916_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='currentBidder',
            field=models.CharField(default='aryanj', max_length=64),
            preserve_default=False,
        ),
    ]
