# Generated by Django 3.1 on 2020-09-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200917_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
