# Generated by Django 3.1 on 2020-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_whenmade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='productKey',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
