# Generated by Django 3.1 on 2020-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200923_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='currentbid',
            name='listing',
        ),
        migrations.AddField(
            model_name='comment',
            name='productKey',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentbid',
            name='productKey',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
