# Generated by Django 3.1 on 2021-01-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210105_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='startingPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
