# Generated by Django 3.1 on 2021-01-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_startingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingPrice',
            new_name='price',
        ),
    ]
